---

- name: Add users to groups
  shell:
    cmd: "egrep -i '^{{ item.1i }}' /etc/group && usermod -a -G {{ item.1 }} {{ item.0.name }} || true"
  with_subelements:
    - "{{ users }}"
    - groups

